// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2024/11/22 22:13:22
const configMerger = require("/Users/songgeng/Project/lollipop/lollipop/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/songgeng/Project/lollipop/lollipop/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/songgeng/Project/lollipop/lollipop/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/songgeng/Project/lollipop/lollipop/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/songgeng/Project/lollipop/lollipop/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/songgeng/Project/lollipop/lollipop/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/songgeng/Project/lollipop/lollipop/plugins/**/*.{js,ts,mjs}","/Users/songgeng/Project/lollipop/lollipop/composables/**/*.{js,ts,mjs}","/Users/songgeng/Project/lollipop/lollipop/utils/**/*.{js,ts,mjs}","/Users/songgeng/Project/lollipop/lollipop/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/songgeng/Project/lollipop/lollipop/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/songgeng/Project/lollipop/lollipop/app.config.{js,ts,mjs}"] } }));

module.exports = config
